swagger: '2.0'
info:
  title: EveMonk back-end API
  description: EveMonk back-end REST API documentation
  version: 1.0.0
  termsOfService: http://evemonk.com/terms
  contact:
    name: Igor Zubkov
    url: http://evemonk.com/support
    email: igor.zubkov@gmail.com
host: evemonk.com
schemes:
  - http
  - https
basePath: /api
consumes:
  - application/json
  - application/x-www-form-urlencoded
produces:
  - application/json
tags:
  - name: sign up
    description: Sign up operations
  - name: sign in
    description: Sign in operations
  - name: sign out
    description: Sign out operations
  - name: sessions
    description: Session operations
  - name: profile
    description: Profile operations

paths:
  /sign_up:
    post:
      summary: Sign up
      description: Sign up endpoint.
      parameters:
        - name: email
          in: formData
          description: User email
          required: true
          type: string
        - name: password
          in: formData
          description: User password
          required: true
          type: string
          format: password
        - name: password_confirmation
          in: formData
          description: User password confirmation
          required: true
          type: string
          format: password
      tags:
        - sign up
      responses:
        '200':
          description: Account created
          schema:
            $ref: '#/definitions/OutputSession'
        '406':
          description: Content type not supported
        '422':
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/Error'

  /sign_in:
    post:
      summary: Get user session with auth token
      description: Signin user and return user session with auth token.
      parameters:
        - name: email
          in: formData
          description: User email
          required: true
          type: string
        - name: password
          in: formData
          description: User password
          required: true
          type: string
          format: password
        - name: name
          in: formData
          description: Session name
          required: false
          type: string
        - name: device
          in: formData
          required: false
          type: string
          enum:
            - ios
            - android
        - name: device_token
          in: formData
          required: false
          type: string
      tags:
        - sign in
      responses:
        '200':
          description: Response with session
          schema:
            $ref: '#/definitions/OutputSession'
        '406':
          description: Content type not supported
        '422':
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/Error'

  /sign_out:
    delete:
      summary: End session
      description: End session
      parameters:
        - name: Authorization
          in: header
          description: 'User auth token. Example: Bearer AAkoMiLatQHMngyuUU1vnh5b'
          default: Bearer ACCESS_TOKEN
          required: true
          type: string
      tags:
        - sign out
      responses:
        '200':
          description: Success
        '401':
          description: Unauthorized

  /sessions:
    get:
      summary: Get all user sessions
      description: Get all user sessions.
      parameters:
        - name: Authorization
          in: header
          description: 'User auth token. Example: Bearer AAkoMiLatQHMngyuUU1vnh5b'
          default: Bearer ACCESS_TOKEN
          required: true
          type: string
        - name: page
          in: query
          description: Page number for pagination
          type: integer
          format: int64
      tags:
        - sessions
      responses:
        '200':
          description: Response with sessions collection
          schema:
            $ref: '#/definitions/OutputSessionCollection'
        '406':
          description: Content type not supported
        '401':
          description: Unauthorized

  /sessions/{id}:
    delete:
      summary: End session
      description: End session
      parameters:
        - name: Authorization
          in: header
          description: 'User auth token. Example: Bearer AAkoMiLatQHMngyuUU1vnh5b'
          default: Bearer ACCESS_TOKEN
          required: true
          type: string
        - name: id
          in: path
          description: Session ID
          required: true
          type: integer
          format: int64
      tags:
        - sessions
      responses:
        '200':
          description: Success
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Session not found

  /profile:
    get:
      summary: Get current user profile
      description: Get current user profile
      parameters:
        - name: Authorization
          in: header
          description: 'User auth token. Example: Bearer AAkoMiLatQHMngyuUU1vnh5b'
          default: Bearer ACCESS_TOKEN
          required: true
          type: string
      tags:
        - profile
      responses:
        '200':
          description: Response with current user
          schema:
            $ref: '#/definitions/OutputUser'
        '401':
          description: Unauthorized
        '406':
          description: Content type not supported

definitions:
  OutputUser:
    required:
      - id
      - email
      - created_at
      - updated_at
    type: object
    properties:
      id:
        type: integer
        format: int64
        description: User ID
      email:
        type: string
        description: User email
      created_at:
        type: string
        description: Created at in ISO8601 format
      updated_at:
        type: string
        description: Updated at in ISO8601 format
    example:
      id: 42
      email: 'me@example.com'
      created_at: '2016-12-12T18:35:59Z'
      updated_at: '2016-12-12T18:36:10Z'

  OutputSession:
    required:
      - id
      - token
      - name
      - device
      - device_token
      - created_at
      - updated_at
    type: object
    properties:
      id:
        type: integer
        format: int64
        description: Session ID
      token:
        type: string
        description: Session token
      name:
        type: string
        description: Session name
      device:
        type: string
        description: Session device type
        enum:
          - ios
          - android
      device_token:
        type: string
        decription: Session device push notification token
      created_at:
        type: string
        description: Created at in ISO8601 format
      updated_at:
        type: string
        description: Updated at in ISO8601 format
    example:
      id: 123
      token: 'AAkoMiLatQHMngyuUU1vnh5b'
      name: 'My Computer'
      device: 'ios'
      device_token: 'ce8be6272e43e85516033e24b4c289220eeda4879c477160b2545e95b68b5969'
      created_at: '2016-12-12T18:35:59Z'
      updated_at: '2016-12-12T18:36:10Z'

  OutputSessionWithoutToken:
    required:
      - id
      - name
      - created_at
      - updated_at
    type: object
    properties:
      id:
        type: integer
        format: int64
        description: Session ID
      name:
        type: string
        description: Session name
      created_at:
        type: string
        description: Created at in ISO8601 format
      updated_at:
        type: string
        description: Updated at in ISO8601 format
    example:
      id: 123
      name: 'My Computer'
      created_at: '2016-12-12T18:35:59Z'
      updated_at: '2016-12-12T18:36:10Z'

  OutputSessionCollection:
    required:
      - collection
      - total_pages
      - current_page
    type: object
    properties:
      collection:
        type: array
        items:
          $ref: '#/definitions/OutputSessionWithoutToken'
      total_pages:
        type: integer
        format: int64
        description: Total pages counter
      current_page:
        type: integer
        format: int64
        description: Current page number

  Error:
    type: object
    properties:
      errors:
        type: array
        items:
          type: string
          description: Error description
